name: "GitHub Classroom Python Pylint Grader"
author: "Rafał Lalik (Rafal.Lalik@uj.edu.pl)"
description: "A plugin for GitHub Classroom's Autograder using pylint to score student code quality."
inputs:
  timeout:
    description: "Duration (in minutes) before the test is terminated. Defaults to 10 minutes with a maximum limit of 60 minutes."
    default: "10"
    required: true
  max-score:
    description: "The maximum amount of points a student can receive for this test."
    required: false
  setup-command:
    description: "Command to execute prior to the test, typically for environment setup or dependency installation."
    required: false
  pylint-args:
    description: "Additional arguments for pylint."
    default: ""
    required: false
  files:
    description: "Files to be checked. Bash-like files list. if FINDALL is present, it will look for all py files in the project including subdirectories."
    default: FINDALL
    required: false
outputs:
  result:
    description: "Runner output"
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/opt/test-runner/bin/run.sh"
  args:
    - "--timeout=${{ inputs.timeout }}"
    - "--max-score=${{ inputs.max-score }}"
    - "--setup-command=${{ inputs.setup-command }}"
    - "--pylint-args=${{ inputs.pylint-args }}"
    - "${{ inputs.files }}"
