name: CI

on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pylint check
        uses: ./
        id: pylint-check
        with:
          timeout: 10
          max-score: 1
          files: tests/*.py runner/*.py
      - name: Decode and assert pylint-check
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token || 'act' }}
          script: |
            // Decode the Base64 output
            const decodedResult = Buffer.from("${{ steps.pylint-check.outputs.result }}", 'base64').toString('utf8');
            console.log(`Decoded Result: ${decodedResult}`);
            const json = JSON.parse(decodedResult)
            if ( !json["version"] ||
                 !json["status"] ||
                 !json["tests"][0]["name"]) {
              throw new Error(`Assertion failed. Expected version, status, and test name to exist, but got '${decodedResult}'`);
            }
