name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git config
        run: |
          git config user.name "Rafał Lalik"
          git config user.email rafal.lalik@uj.edu.pl
      - name: Tag and push v1
        run: |
          git tag -f v1 # Since we are already on releases/v1 we don't need a ref. This will tag HEAD of releases/v1.
          git push origin v1 --force
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1
          allowUpdates: true
